image:
  file: .gitpod.Dockerfile

ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
- port: 8050 # Dash App
  onOpen: open-preview
- port: 8888 # Jupyter Notebook
  onOpen: open-browser

tasks:
  - init: |
      pip install -r requirements.txt
      pip install pyppeteer  nbconvert[webpdf] nbconvert[qtpdf]
      sudo cp -r .jupyter /home/gitpod/
    command: |
      python dash_intro.py
  - command: gp await-port 8050 && sleep 2 && gp preview "$(gp url 8050)"
